name: 'Pull Request on Dev environment'

on:
  pull_request:
    branches:
      - main
    paths:
      - 'dev/**'

jobs: 
  pr-infra-check:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ./dev
        
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    # Install the latest version of Terraform CLI 
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      
    # Run Terraform init
    - name: Terraform Init
      id: init
      run: terraform init